import { MyButton, ButtonType } from "./framework/widgets.slint";
import { AppBackend, AppState, Printer } from "app.slint";

export component Title inherits Rectangle {
    in-out property <string> text;
    height: 40px;
    background: @linear-gradient(180deg, #1a1c24 0%, #101116 100%);
    border-width: 0px;
    Text {
        vertical-alignment: center;
        horizontal-alignment: center;
        height: 40px;
        text: text;
        font-size: 20px;
        font-weight: 700;
        color: #ffffff;
    }
}

export component SelectPrinterButton inherits MyButton {
    in-out property <Printer> printer;
    type: ButtonType.RadioButton;
    height: 56px;
    horizontal-alignment: left;
    text-padding: 12px;
}

export component SelectPrinter inherits Rectangle {
    callback selected;
    background: #0b0c10;
    VerticalLayout {
        Title {
            text: "Select Printer";
        }
        VerticalLayout {
            padding: 5px;
            spacing: 5px;
            for printer[index] in AppState.available_printers: SelectPrinterButton {
                printer: printer;
                height: 60px;
                pushed: AppState.curr_printer == index;
                text: (AppState.curr_printer == index ? "  ✓ " : "      ") + printer.name + (AppState.default_printer == index ? " (Default)" : "") + (printer.connected ? ": Connected" : ": Disconnected");
                clicked => {
                    AppBackend.select-printer(printer.id);
                    selected();
                }
            }
        }
    }
}
